- name: install doxker from repo
  hosts: myhosts
  become: yes
  vars_files:
    - user
  tasks:
    - name: install ca-certificates curl
      ansible.builtin.apt:
        pkg:
        - ca-certificates
        - curl
        update_cache: yes
    - name: add docker dir
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: donnwload key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r
    - name: inst rep
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        state: present
    - name: install docker
      ansible.builtin.apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        update_cache: yes
    - name: run docker non root user
      ansible.builtin.group:
        name: docker
        state: present 
    - name: add user
      ansible.builtin.user:
        name: "{{ user }}"
        groups: docker
        append: yes
