- name: add user for system and make for hi root
  hosts: myhosts
  become: yes
  tasks:
    - name: add user in system
      ansible.builtin.user:
        name: Bob
        password: cot 
        groups: sudo
    - name: messeng
      ansible.builtin.debug:
        msg: Hello World
