- name: add user for system and make for hi root
  hosts: myhosts
  become: yes
  vars_files:
    - user
  tasks:
    - name: add user in system
      ansible.builtin.user:
        name: "{{user}}"
        password: "{{pass}}"
        append: true
        groups: "{{group}}"
        create_home: yes


